### PR TITLE
Misc. fixes for netstandard

### PR DESCRIPTION
**Pull request by jasonwilliams200OK**
This PR:
- provides alternative `[Read/Write]Async` overloads for net45 and netstandard TFMs in FileAppender.

- covers some minor code feedback given at https://github.com/apache/log4net/pull/16 and code cleanup.

---

FYI: to build the project with .NET CLI on various platforms (downloadable from https://dot.net/core), run the following sequence of commands:

```sh
git clone https://github.com/apache/log4net --recursive
cd log4net/netstandard

dotnet restore

dotnet test log4net.tests    # this will build log4net.tests,
                             # it's dependency log4net and run tests; all in one command!
```

I have tested on macOS and Windows and the test result is consistent:

> Test Count: 145, Passed: 107, Failed: 30, Inconclusive: 0, Skipped: 8

/cc @bodewig

### CODE REVIEW

**Comment by bodewig** [comment]
by fixing `FileAppender` I'm now causing a merge conflict here, sorry.

**Comment by jasonwilliams200OK** [comment]
I have rebased it against trunk. To review without whitespace diff, here is the proper diff link: https://github.com/apache/log4net/pull/30/files?w=1

**Comment by bodewig** [comment]
Thanks, I think I had this figured out myself already.

Unfortunately it turns out the way we build the 4.5 version isn't working as intended (we tell Nant to build against 4.0 on a machine with 4.5 installed, but this doesn't find the `ReadAsync` override you've added). I'll need a way to trick NAnt into working, I'm afraid.

**Comment by jasonwilliams200OK** [comment]
Oh, in other words Nant is having issue parsing this preprocessor directive: `#if NET_4_5 || NETSTANDARD1_3`?

**Comment by bodewig** [comment]
No, NAnt seems to compile against 4.0's libraries where `Stream.ReadAsync` hasn't been defined.

**Pull request closed without merging**
