### PR TITLE
fix bug with m_preserveLogFileNameExtension and m_staticLogFileName

### PR DESCRIPTION
**Pull request by n1l**
Hi! I think that I found a bug.

This code is example to show you, that file rolling is not happening

`class Program
  {
    public static void Main(string[] args)
    {
      var log = Logger.Create();
      for (int i = 0; i < 1000; i++)
      {
        log.Debug(Enumerable.Range(50, 50)
          .Select(x => x.ToString())
          .Aggregate(string.Empty, (x, y) => x + ' ' + y));
      }

```
}
```

  }
  public class Logger
  {
    public Logger()
    {
    }

```
public void AddAppender(IAppender appender)
{
  Hierarchy hierarchy =
    (Hierarchy)LogManager.GetRepository();

  hierarchy.Root.AddAppender(appender);
}

static Logger()
{
  Hierarchy hierarchy = (Hierarchy)LogManager.GetRepository();
  TraceAppender tracer = new TraceAppender();
  PatternLayout patternLayout = new PatternLayout();

  patternLayout.ActivateOptions();

  tracer.Layout = patternLayout;
  tracer.ActivateOptions();
  hierarchy.Root.AddAppender(tracer);
  RollingFileAppender roller = new RollingFileAppender();
  roller.StaticLogFileName = false;
  roller.Layout = patternLayout;
  roller.AppendToFile = true;
  roller.RollingStyle = RollingFileAppender.RollingMode.Composite;
  roller.DatePattern = "dd_MM_yyyy";
  roller.MaxSizeRollBackups = 2;
  roller.CountDirection = 1;
  roller.PreserveLogFileNameExtension = true;
  roller.MaximumFileSize = "10KB";
  roller.File = @"D:\Projects\Contrib\Work\LoggingTestApp\LOGS\mylog_.log";
  roller.ActivateOptions();
  hierarchy.Root.AddAppender(roller);

  hierarchy.Root.Level = Level.All;
  hierarchy.Configured = true;
}

public static ILog Create()
{
  return LogManager.GetLogger("");
}
```

  }`

I fixed this, please review my code.
Thanks.

Log4net - 1.2.15, or from trunk

### CODE REVIEW

**Comment by bodewig** [comment]
log4net has moved to git at Apache and as a result this repository is going to be deleted within the coming weeks. Please re-create the pull request in https://github.com/apache/logging-log4net if you still feel it is relevant.

**Comment by bodewig** [comment]
I think https://github.com/apache/logging-log4net/commit/ce481db1bf3b556c7ebe7851546c9425d0b5c192 should do the same as this PR.

**Comment by n1l** [comment]
Thanks! I think this can be tested with my example code in first post.

**Comment by bodewig** [comment]
I think https://github.com/apache/logging-log4net/commit/f8b7290065f16c7fce5b54a2d2c348b16e20ab4e is a unit test version of your example code. Does this look correct for you @n1l ?

**Comment by n1l** [comment]
It seems ok. Thanks!

**Comment by bodewig** [comment]
Many thanks. I've merged the branch to master, could you please close this PR?

**Comment by n1l** [comment]
Closed.

**Pull request closed without merging**
