### PR TITLE
Wip/app settings

### PR DESCRIPTION
**Pull request by JJoe2**
Implementation for LOG4NET-526

### CODE REVIEW

**Comment by JJoe2** [comment]
I'll rebase this after #36 and #37 have been processed.

**Comment by bodewig** [comment]
Am I correct that `AppSettingPatternConverter` and the few changes in `PatternString` are the only relevant code changes (along with adding the new filte to the solution files)? If so, I can pick up the file myself, no need to rebase the PR.

**Comment by JJoe2** [comment]
Hi Stefan,

That's correct, those are the only changes.

Thanks,

________________________________

**Comment by bodewig** [comment]
I've added your converter, many thanks.

Tests would be good and we need documentation before we can close LOG4NET-526.

**Comment by JJoe2** [comment]
I’ll be happy to do the unit tests and possibly the doc.   Are suitable XML comments enough?

Now this is added, I’ll also be thinking about the next step, which is to allow the PatternString converter to be used in the XML configuration file for properties of types other than strings.
So that I can do something like:

    <root>
       <level type=”log4net.Util.PatternString” value="%appsetting{Logging. Level}" />
   </root>

Should be possible: basically be applying the PatternString conversion before converting to the target type of the property.

**Comment by bodewig** [comment]
I've just realized there is no documentation outside of the API docs for the other `PatternStringConverter`s either, so yes, XML comments should be sufficient - and you've already provided that. I thought there was a section inside the manual on the web site, but don't find anything.

**Pull request closed without merging**
