### PR TITLE
Use UTC internally to avoid ambiguous timestamps

### PR DESCRIPTION
**Pull request by JJoe2**
Resubmitting replacement for #24 

Rebased to latest trunk and fixed backwards compatibility issue of binary serialization of LoggingEvent.

### CODE REVIEW

**Comment by bodewig** [comment]
@JJoe2 I'm not sure whether you're subscribed to the dev list, you better should be.

Dominik Psenner raised a few questions about different options, see https://lists.apache.org/thread.html/4d354e8ec17a40bb768cc8691289ac78046449e4148f18256f7a110e@%3Clog4net-dev.logging.apache.org%3E and a follow up email.

**Comment by JJoe2** [comment]
Closing for now - in its current form it's a breaking change - it changes LoggingEvent.DateTime from a field to a property.

**Comment by JJoe2** [comment]
Reopened - fixed breaking change.

**Comment by bodewig** [comment]
I've created LOG4NET-530 so it becomes easier to create the release notes by looking in one place only.

Many thanks, @JJoe2

**Pull request closed without merging**
