### PR TITLE
Fixes for the LogicalThreadContext

### PR DESCRIPTION
**Pull request by ahouben**
The current implementation of `LogicalThreadContext` does not flow correctly through `async/await` calls as described in http://stackoverflow.com/questions/23316743/log4net-logicalthreadcontext-not-working-as-expected.

This fix honors the shallow-copy-on-write behavior and immutable requirements when using `CallContext.Logical{Get,Set}Data`. Please see the accompanied `LogicalThreadContextTest` which is a copy of `ThreadContextTest` but adds `TestLogicalThreadPropertiesPatternAsyncAwait` and `TestLogicalThreadStackPatternAsyncAwait` to demonstrate the fix.

Thanks to @stephen-cleary for all the good information on the inner workings of the async/await mechanism all over the internet.

### CODE REVIEW

**Comment by bodewig** [comment]
FWIU the code should be compilable for .NET 4.0 but the changes will only fix the problem on 4.5 (and there is no fix for 4.0).

We'll likely need additional constants and conditionally compile the new unit tests on 4.5 only, which may become tricky since NAnt doesn't support .NET 4.5 as a target framework, yet.

**Comment by ahouben** [comment]
Would it make sense to update the patch with the following modifications then:

 

·        Create a new top level src/log4net/log4net.vs2012.sln derived from log4net.vs2010.sln with the following changes:

o   targets .NET 4.5

o   includes exactly the same sources as log4net.vs2010.sln

o   defines an additional conditional compilation symbol FRAMEWORK_4_5_OR_ABOVE which is used to conditionally execute the new unit tests in the patch (Task.WhenAll used in the tests does not exist prior to .NET 4.5)

·        Add a runtime check when accessing LogicalThreadContext.{Stacks,Properties} which refuses to run is the underlying .NET runtime is not at least 4.5

**Comment by bodewig** [comment]
I'm fine with the first batch of changes you propose but don't think we should thrown an exception on .NET 4.0.  I've opened [LOG4NET-455](https://issues.apache.org/jira/browse/LOG4NET-455) for tracking this PR.

**Comment by ahouben** [comment]
The PR was updated to reflect the aforementioned changes:
* Create a new top level src/log4net/log4net.vs2012.sln derived from log4net.vs2010.sln with the following changes:
  * targets .NET 4.5
  * includes exactly the same sources as log4net.vs2010.sln
  * defines an additional conditional compilation symbol FRAMEWORK_4_5_OR_ABOVE which is used to conditionally execute the new unit tests in the patch (Task.WhenAll used in the tests does not exist prior to .NET 4.5)
  * revert log4net.[Tests.]vs2010.sln to target .NET 4.0

**Comment by bodewig** [comment]
I had to tweak things a little to make it build on Mono and it looks as if I had to do a little bit more for .NET 2.0, these will be follow up commits.

**Comment by maxcherednik** [comment]
Hi,
I was playing around with this fix recently and came across some strange behavior.
Imagine main method:

    using (LogicalThreadContext.Stacks["NDC"].Push("Start"))
    {
        // init all the stuff here
        _timer.TimerElapsed += TimerOnTimerElapsed;
    }

An that would be it.

Then I on the timer tick event I have another context:

    using (LogicalThreadContext.Stacks["NDC"].Push("timer"))
    {
        Logger.Info("I am doing something here. Show me the context");
    }

As a result expect to see the context of the timer like this: "timer", 
instead, I see: "Start timer"

Is this correct behavior?

**Comment by maxcherednik** [comment]
To my previous comment - I guess this behavior is by design.
This is the same way as in this [article!] (http://blog.stephencleary.com/2013/04/implicit-async-context-asynclocal.html)

**Pull request closed without merging**
